/** Locale-owned UI copy for the first Simplified Chinese ORYH workbench. */
export const zhCN = {
  productName: 'ORYH AI Client',
  productDescriptor: '企业工作台',
  loading: '正在加载本地工作台…',
  retry: '重试',
  connected: '已连接',
  noConnection: '尚未连接企业',
  chooseConnection: '选择企业',
  myWork: '我的工作',
  directActions: '直接操作',
  directActionsDescription: '直接操作运行固定的 ORYH 业务程序。',
  savedActions: '已保存操作',
  connection: '企业连接',
  connectEnterprise: '连接企业',
  connectAnotherAccount: '连接其他账号',
  switchAccountHelp: '授权页会使用当前 ORYH 浏览器账号。若需更换账号，请先在 ORYH Console 中退出并登录目标账号，再确认本次授权。',
  origin: 'ORYH 服务地址',
  originHelp: '输入 ORYH 官网或自部署服务器的完整地址，建议使用 HTTPS。',
  startConnection: '开始连接',
  approvalTitle: '在浏览器中确认此设备',
  approvalDescription: 'ORYH 会将此设备绑定到当前登录账号。客户端不会显示或复制访问凭据。',
  openApproval: '打开授权页面',
  userCode: '设备短码',
  waitingApproval: '等待浏览器授权',
  cancel: '取消',
  disconnect: '断开本地连接',
  disconnectTitle: '断开当前企业连接？',
  disconnectDescription: '这会从本机钥匙串和工作台移除当前企业账号的访问凭据与已保存操作，不会退出 ORYH Console 的浏览器登录。',
  operationReady: '选择一个直接操作',
  operationReadyDescription: '常用业务视图直接调用已登记的 ORYH 操作，不需要模型生成调用代码。',
  refresh: '刷新',
  reuse: '复用结果',
  save: '保存操作',
  saveLabel: '保存操作名称',
  savePlaceholder: '例如：项目列表',
  saveHelp: '保存的是固定的业务操作，不会保存访问凭据或任意 API 代码。',
  noSavedActions: '尚未保存操作。运行一个业务视图后，可将其固定在这里。',
  runSaved: '直接刷新',
  openConsole: '打开 ORYH Console',
  projects: '项目列表',
  todos: '我的待办',
  expenseClaims: '我的费用申请',
  total: '共 {count} 项',
  refreshedAt: '刷新于 {time}',
  projectEmpty: '当前企业没有可见项目。',
  todoEmpty: '当前员工没有开放待办。',
  expenseClaimEmpty: '当前员工没有费用申请。',
  projectCode: '编号',
  projectName: '项目',
  projectClient: '客户',
  projectStatus: '状态',
  todoTitle: '待办',
  todoTarget: '关联对象',
  todoDueAt: '到期时间',
  todoStatus: '状态',
  submittedAt: '提交于 {time}',
  notSubmitted: '尚未提交',
  noValue: '未填写',
  resultReuseHint: '复用结果不发送新的 ORYH 请求，也不会调用模型。',
  savedOperationHint: '已保存操作属于当前企业，切换企业后不会被自动复用。',
  genericError: '本地工作台暂时无法完成该操作。',
  employeeRequired: '当前 ORYH 账号没有关联员工记录，无法读取仅属于员工的待办或费用申请。请改用关联员工的账号，或在 ORYH Console 中完成员工关联。',
  connectionIdentityMismatch: '当前 ORYH 凭据不再属于这个本地企业连接。为防止跨企业操作，客户端已阻止访问；请断开后重新连接正确的 ORYH 账号。',
  directView: '确定性业务视图',
  close: '关闭',
  switchToDarkTheme: '切换到深色外观',
  switchToLightTheme: '切换到浅色外观',
} as const

/** Replace one named message placeholder with plain displayed text. */
export function format(message: string, values: Record<string, string | number>): string {
  return message.replace(/\{([a-zA-Z]+)\}/gu, (_, key: string) => String(values[key] ?? ''))
}
