import type { ChatNavigation } from '@oryh/dsh-host/types'
import { TimesheetChat } from './timesheet-chat.js'
import { useEffect, useRef, useState } from 'react'
import { Button, Dialog, DialogActions, DialogBody, DialogContent, DialogSurface, DialogTitle } from '@fluentui/react-components'
import type { ConnectionSummary, TimesheetAction, TimesheetDetail, TimesheetFields, TimesheetHeader, TimesheetIntent, TimesheetLine, TimesheetOptions, TimesheetTodo } from '@oryh/ai-client-core/types'
import { useOryhRemote } from './remote.js'
import { useText } from './locale.js'
const today=()=>new Date().toLocaleDateString('en-CA')
const blankLine=():TimesheetLine=>({work_date:today(),hours:0,work_type:'',project_id:'',task:'',notes:''})
const blank=():TimesheetFields=>({period_start:today(),period_end:today(),source_report_text:'',entries:[blankLine()]})
const sum=(entries:TimesheetLine[])=>Number(entries.reduce((n,l)=>n+(Number(l.hours)||0),0).toFixed(6))
export function TimesheetPanel({connection,manager,active,navigationId,navigation,onDirtyChange}:{connection:ConnectionSummary;manager:boolean;active:boolean;navigationId?:string;navigation?:ChatNavigation;onDirtyChange:(v:boolean)=>void}) {
  const api=useOryhRemote(),t=useText(),alive=useRef(true)
  const [headers,setHeaders]=useState<TimesheetHeader[]>([]),[todos,setTodos]=useState<TimesheetTodo[]>([]),[history,setHistory]=useState<TimesheetIntent[]>([])
  const [options,setOptions]=useState<TimesheetOptions>({workTypes:[],projects:[],requirements:[],editableStates:[],submitStates:[]}),[detail,setDetail]=useState<TimesheetDetail>(),[todoId,setTodoId]=useState<string>()
  const [editor,setEditor]=useState(false),[fields,setFields]=useState(blank),[editing,setEditing]=useState<{entryId?:string;line:TimesheetLine}>(),[dirty,setDirty]=useState(false)
  const [loaded,setLoaded]=useState(false)
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[review,setReview]=useState<TimesheetIntent>(),[query,setQuery]=useState('')
  const [decision,setDecision]=useState<'approved'|'rejected'|'returned'>('approved'),[comment,setComment]=useState('')
  useEffect(()=>{alive.current=true;void run(refresh);return()=>{alive.current=false}},[])
  useEffect(()=>{onDirtyChange(dirty || busy);return()=>onDirtyChange(false)},[dirty,busy,onDirtyChange])
  useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty])
  const handledNavigation=useRef<string>()
  const [openedNavigationId,setOpenedNavigationId]=useState<string>()
  useEffect(()=>{
    if(!navigationId||!active||!loaded||busy||handledNavigation.current===navigationId)return
    handledNavigation.current=navigationId
    if(navigation?.headerId){if(dirty){setError('当前有未保存修改，请保存或放弃后重新要求打开工时。');return}void run(async()=>{await open(navigation.headerId!,navigation.todoId);if(alive.current)setOpenedNavigationId(navigationId)});return}
    if(manager)return
    if(editor){setOpenedNavigationId(navigationId);return}
    if(dirty)return
    setFields(blank());setEditor(true);setDetail(undefined);setEditing(undefined);setDirty(true);setOpenedNavigationId(navigationId)
  },[navigationId,active,busy,loaded])
  async function run(fn:()=>Promise<void>) {if(busy)return;setBusy(true);setError('');try{await fn()}catch(e){if(alive.current)setError(e instanceof Error?e.message:t('tsFailed'))}finally{if(alive.current)setBusy(false)}}
  async function refresh() {const [hs,ts,opts,log]=await Promise.all([manager?Promise.resolve([]):api.timesheetList(connection.id),manager?api.timesheetQueue(connection.id):Promise.resolve([]),api.timesheetOptions(connection.id),api.timesheetHistory(connection.id)]);if(alive.current){setHeaders(hs);setTodos(ts);setOptions(opts);setHistory(log);setLoaded(true)}}
  async function open(id:string,tid?:string) {const d=await api.timesheetDetail(connection.id,id,tid);if(alive.current){setDetail(d);setTodoId(tid);setComment('');setEditor(false);setEditing(undefined);setReview(undefined);setMessage('');setDirty(false)}}
  async function prepare(action:TimesheetAction){const r=await api.timesheetPrepare(connection.id,action);if(alive.current){setReview(r);setHistory(h=>[r,...h.filter(x=>x.id!==r.id)])}}
  function change(f:TimesheetFields){setFields(f);setDirty(true);setReview(undefined)}
  function renderLines(entries:TimesheetLine[]) {const daily=new Map<string,number>();entries.forEach(e=>daily.set(e.work_date,(daily.get(e.work_date)??0)+e.hours));return <><div className="table-scroll"><table><thead><tr>{['tsDate','tsHours','tsType','tsProject','tsTask','tsNotes'].map(k=><th key={k}>{t(k as 'tsDate')}</th>)}</tr></thead><tbody>{entries.map((e,i)=><tr key={i}><td>{e.work_date}</td><td>{e.hours}</td><td>{options.workTypes.find(o=>o.name===e.work_type)?.title||e.work_type||'—'}</td><td>{options.projects.find(o=>o.id===e.project_id)?.name||('projectName' in e ? String(e.projectName) : '')||e.project_id||'—'}</td><td>{e.task||'—'}{'client' in e && Boolean(e.client) && <p>{String(e.client)}</p>}</td><td>{e.notes||'—'}</td></tr>)}</tbody></table></div><p><strong>{t('tsTotal')}：{sum(entries)}</strong></p><p>{t('tsDaily')}：{[...daily].sort().map(([d,n])=>`${d} · ${Number(n.toFixed(6))}h`).join(' / ')}</p></>}
  function lineForm(l:TimesheetLine,onChange:(l:TimesheetLine)=>void,dateLocked=false){return <div className="oryh-ts-fields"><label>{t('tsDate')}<input type="date" required value={l.work_date} disabled={dateLocked} onChange={e=>onChange({...l,work_date:e.target.value})}/></label><label>{t('tsHours')}<input type="number" min="0" max="24" step="any" required value={l.hours||''} onChange={e=>onChange({...l,hours:Number(e.target.value)})}/></label><label>{t('tsType')}<select required value={l.work_type} onChange={e=>onChange({...l,work_type:e.target.value})}><option value="">{t('tsNone')}</option>{options.workTypes.map(o=><option key={o.name} value={o.name}>{o.title}</option>)}</select></label><label>{t('tsProject')}<select value={l.project_id} onChange={e=>onChange({...l,project_id:e.target.value})}><option value="">{t('tsNone')}</option>{options.projects.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>{t('tsTask')}<input maxLength={200} value={l.task} onChange={e=>onChange({...l,task:e.target.value})}/></label><label>{t('tsNotes')}<textarea maxLength={2000} value={l.notes} onChange={e=>onChange({...l,notes:e.target.value})}/></label></div>}
  const panel=useRef<HTMLElement>(null), listScroll=useRef(0), previousDetail=useRef(false)
  useEffect(()=>{const seat=panel.current?.closest<HTMLElement>('.oryh-business-seat');const showing=editor||Boolean(detail);if(seat&&showing!==previousDetail.current){if(showing){listScroll.current=seat.scrollTop;seat.scrollTop=0;panel.current?.querySelector<HTMLButtonElement>('.business-page-header button')?.focus({preventScroll:true})}else seat.scrollTop=listScroll.current}previousDetail.current=showing},[editor,detail])
  const actionTitle=(a:TimesheetAction)=>t(a.kind==='create'?'tsCreate':a.kind==='submit'?'tsSending':a.kind==='approve'?'tsApprovalAction':a.kind==='add-line'?'tsAdd':a.kind==='edit-line'?'tsEdit':'tsRemove')
  return <section ref={panel} className="oryh-timesheets" aria-busy={busy}>
    <header className="business-page-header">{(editor||detail)&&<Button disabled={busy||dirty} onClick={()=>{setDetail(undefined);setEditor(false);setEditing(undefined);setReview(undefined)}}>返回列表</Button>}<h1>{editor?t('tsNew'):detail?`${detail.header.period_start} — ${detail.header.period_end}`:t(manager?'tsApprovals':'tsMine')}</h1>{dirty&&<span className="muted">请先保存或放弃当前修改</span>}</header>
    {active&&<TimesheetChat navigationReady={openedNavigationId===navigationId} connectionId={connection.id} manager={manager} {...(navigationId?{navigationId}:{})} localEdits={JSON.stringify({editing,decision,comment,query,busy,detail,visibleRows:editor||detail?[]:manager?todos.filter(r=>`${r.title} ${r.description}`.includes(query)):headers.filter(r=>`${r.period_start} ${r.period_end} ${r.status}`.includes(query))})} busy={busy} dirty={dirty} {...(editor?{fields}:{})} {...(detail?{headerId:detail.header.id}:{})} {...(todoId?{todoId}:{})} onApply={action=>{
      if(action.kind==='create'&&action.fields){setFields(action.fields);setEditor(true);setDetail(undefined);setEditing(undefined);setDirty(true);setReview(undefined)}
      else void run(()=>prepare(action))
    }}/> }
    {!editor&&!detail&&<div className="toolbar"><Button disabled={busy} onClick={()=>void run(refresh)}>{t('tsRefresh')}</Button>{!manager&&<Button appearance="primary" disabled={busy||dirty} onClick={()=>{setFields(blank());setEditor(true);setDetail(undefined);setEditing(undefined);setDirty(true)}}>{t('tsNew')}</Button>}<input aria-label={t('tsSearch')} placeholder={t('tsSearch')} value={query} onChange={e=>setQuery(e.target.value)}/></div>}
    {!editor&&!editing&&!review&&<>{busy&&<p role="status">{t('tsLoading')}</p>}{error&&<p role="alert">{error}</p>}</>}{message&&<p role="status">{message}</p>}

    {!editor&&!detail&&<div className="surface table-surface"><div className="table-scroll"><table><thead><tr><th>{manager?t('tsApprovals'):t('tsStart')}</th><th>{manager?t('tsNotes'):t('tsEnd')}</th><th>{t(manager?'tsTodoStatus':'tsStatus')}</th><th>{t('tsAction')}</th></tr></thead><tbody>{manager?todos.filter(r=>`${r.title} ${r.description}`.includes(query)).map(r=><tr key={r.id}><td>{r.title}</td><td>{r.description}</td><td>{t('tsOpenState')}</td><td><Button disabled={busy||dirty} onClick={()=>void run(()=>open(r.entity_id,r.id))}>{t('tsOpen')}</Button></td></tr>):headers.filter(r=>`${r.period_start} ${r.period_end} ${r.status}`.includes(query)).map(r=><tr key={r.id}><td>{r.period_start}</td><td>{r.period_end}</td><td>{r.status}</td><td><Button disabled={busy||dirty} onClick={()=>void run(()=>open(r.id))}>{t('tsOpen')}</Button></td></tr>)}</tbody></table>{!(manager?todos:headers).length&&<p>{t('tsEmpty')}</p>}</div></div>}
    {dirty&&<p>{t('tsGuard')} <Button disabled={busy} onClick={()=>{setDirty(false);setEditor(false);setEditing(undefined);setComment('');setReview(undefined)}}>{t('tsDiscard')}</Button></p>}
    {editor&&<form className="surface" onInvalidCapture={()=>setError(t('tsInvalid'))} onSubmit={e=>{e.preventDefault();void run(()=>prepare({kind:'create',fields}))}}><fieldset disabled={busy}><legend>{t('tsNew')}</legend><div className="oryh-ts-fields"><label>{t('tsStart')}<input required type="date" value={fields.period_start} onChange={e=>change({...fields,period_start:e.target.value})}/></label><label>{t('tsEnd')}<input required type="date" value={fields.period_end} onChange={e=>change({...fields,period_end:e.target.value})}/></label><label>{t('tsNarrative')}<textarea maxLength={10000} value={fields.source_report_text} onChange={e=>change({...fields,source_report_text:e.target.value})}/></label></div>{fields.entries.map((l,i)=><fieldset key={i}><legend>{i+1}</legend>{lineForm(l,v=>change({...fields,entries:fields.entries.map((x,j)=>i===j?v:x)}))}<Button disabled={fields.entries.length===1} onClick={()=>change({...fields,entries:fields.entries.filter((_,j)=>j!==i)})}>{t('tsRemove')}</Button></fieldset>)}<Button disabled={fields.entries.length>=100} onClick={()=>change({...fields,entries:[...fields.entries,blankLine()]})}>{t('tsAdd')}</Button><p>{t('tsTotal')}：{sum(fields.entries)}</p><div className="oryh-ts-save-feedback">{error&&!review&&<p role="alert">{error}</p>}{busy&&!review&&<p role="status">{t('tsChecking')}</p>}<Button appearance="primary" type="submit">{t(busy?'tsChecking':'tsReview')}</Button></div><p>{t('tsSavedDraft')}</p></fieldset></form>}
    {detail&&<div className="surface"><h2>{detail.canEdit&&!manager?'编辑工时':'工时详情 · 只读'}</h2>{!detail.canEdit&&<p>当前身份或单据状态不允许修改工时内容。</p>}<p>{t('tsEmployee')}：{detail.header.employee_id} · {t('tsStatus')}：{detail.header.status}</p><p>{detail.header.source_report_text}</p>{detail.canEdit&&!manager?<p>{t('tsTotal')}：{sum(detail.entries)}</p>:renderLines(detail.entries)}
      {!manager&&detail.canEdit&&<div className="toolbar"><Button disabled={busy||dirty||!options.submitStates.includes(detail.header.status)} onClick={()=>void run(()=>prepare({kind:'submit',headerId:detail.header.id}))}>{t('tsSubmit')}</Button>{detail.canEdit&&<Button disabled={busy||dirty} onClick={()=>{setEditing({line:{...blankLine(),work_date:detail.header.period_start}});setDirty(true)}}>{t('tsAdd')}</Button>}</div>}
      {!manager&&detail.canEdit&&detail.entries.map(l=><form key={l.id} onSubmit={e=>{e.preventDefault();if(editing?.entryId===l.id)void run(()=>prepare({kind:'edit-line',headerId:detail.header.id,entryId:l.id,line:editing.line}))}}><fieldset disabled={busy||Boolean(editing&&editing.entryId!==l.id)}><legend>{l.work_date} · {t('tsEdit')}</legend>{lineForm(editing?.entryId===l.id?editing.line:l,v=>{setEditing({entryId:l.id,line:v});setDirty(true);setReview(undefined)},true)}{editing?.entryId===l.id&&error&&!review&&<p role="alert">{error}</p>}<Button type="submit" appearance="primary" disabled={editing?.entryId!==l.id}>{t(busy?'tsChecking':'tsReview')}</Button><Button disabled={dirty} onClick={()=>void run(()=>prepare({kind:'delete-line',headerId:detail.header.id,entryId:l.id}))}>{t('tsRemove')}</Button></fieldset></form>)}
      {editing&&!editing.entryId&&<form onSubmit={e=>{e.preventDefault();void run(()=>prepare({kind:editing.entryId?'edit-line':'add-line',headerId:detail.header.id,...(editing.entryId?{entryId:editing.entryId}:{}),line:editing.line}))}}><fieldset disabled={busy}><legend>{t('tsEdit')}</legend>{lineForm(editing.line,v=>{setEditing({...editing,line:v});setDirty(true);setReview(undefined)},Boolean(editing.entryId))}{editing.entryId&&<p>{t('tsNoDateEdit')}</p>}{error&&!review&&<p role="alert">{error}</p>}<Button type="submit" appearance="primary">{t(busy?'tsChecking':'tsReview')}</Button></fieldset></form>}
      <details><summary>{t('tsTrail')}</summary>{detail.approval_records.map(a=><p key={a.id}>{t('tsRound')} {a.round_no}/{a.sequence_no} · {a.action} · {a.approver_id} · {a.acted_at}<br/>{a.comment}</p>)}</details>
      {manager&&<form onSubmit={e=>{e.preventDefault();void run(()=>prepare({kind:'approve',headerId:detail.header.id,todoId:todoId!,decision,comment}))}}><fieldset disabled={busy}><legend>{t('tsDecision')}</legend><label>{t('tsDecision')}<select value={decision} onChange={e=>{setDecision(e.target.value as typeof decision);setDirty(true);setReview(undefined)}}><option value="approved">{t('tsApprove')}</option><option value="rejected">{t('tsReject')}</option><option value="returned">{t('tsReturn')}</option></select></label><label>{t('tsComment')}<textarea required maxLength={2000} value={comment} onChange={e=>{setComment(e.target.value);setDirty(true);setReview(undefined)}}/></label><p>{t('tsApprovalBoundary')}</p><Button type="submit" appearance="primary">{t('tsReviewDecision')}</Button></fieldset></form>}
    </div>}
    <details className="surface"><summary>{t('tsRequirements')}</summary>{options.requirements.length?options.requirements.map((r,i)=><pre key={i}>{r}</pre>):<p>{t('tsRuleEmpty')}</p>}</details>
    <details className="surface"><summary>{t('tsHistory')}</summary>{history.filter(r=>manager?r.action.kind==='approve':r.action.kind!=='approve').map(r=><div key={r.id}><p>{actionTitle(r.action)} · {new Date(r.updatedAt).toLocaleString()} · {t(r.state==='review'?'tsReviewState':r.state==='done'?'tsDoneState':r.state==='failed'?'tsFailed':'tsUnknownState')}<br/>{r.message}</p>{r.state==='review'&&<Button disabled={busy||dirty} onClick={()=>void run(()=>prepare(r.action))}>{t('tsResume')}</Button>}{['unknown','executing'].includes(r.state)&&<Button disabled={busy} onClick={()=>void run(async()=>{const n=await api.timesheetReconcile(connection.id,r.id,r.revision);if(alive.current){setMessage(n.message);setHistory(h=>h.map(x=>x.id===n.id?n:x))}})}>{t('tsReconcile')}</Button>}</div>)}</details>
    <Dialog open={Boolean(review)} onOpenChange={(_,d)=>{if(!d.open&&!busy)setReview(undefined)}}><DialogSurface className="oryh-timesheet-review"><DialogBody><DialogTitle>{t('tsReviewTitle')} · {review&&actionTitle(review.action)}</DialogTitle><DialogContent><p>{connection.identity.tenant.name??connection.identity.tenant.slug} · {connection.identity.user.email}</p>{review?.detail&&<><p>{t('tsEmployee')}：{review.detail.header.employee_id} · {review.detail.header.period_start} — {review.detail.header.period_end}</p><p>{review.detail.header.source_report_text}</p>{renderLines(review.detail.entries)}</>}{review?.action.fields&&<><p>{review.action.fields.period_start} — {review.action.fields.period_end}</p><p>{review.action.fields.source_report_text}</p>{renderLines(review.action.fields.entries)}</>}{review?.action.line&&<><h3>{actionTitle(review.action)}</h3>{renderLines([review.action.line])}</>}{review?.action.kind==='delete-line'&&<p>{t('tsDeleteWarning')} {review.detail?.entries.find(e=>e.id===review.action.entryId)?.work_date} · {review.detail?.entries.find(e=>e.id===review.action.entryId)?.task}</p>}{review?.action.kind==='approve'&&<><p><strong>{t(review.action.decision==='approved'?'tsApprove':review.action.decision==='rejected'?'tsReject':'tsReturn')}</strong>：{review.action.comment}</p><p>{t('tsApprovalBoundary')}</p></>}</DialogContent>{error&&<p role="alert">{error}</p>}{busy&&<p role="status">{t('tsLoading')}</p>}<DialogActions><Button disabled={busy} onClick={()=>setReview(undefined)}>{t('tsCancel')}</Button><Button appearance="primary" disabled={busy||!review||review.expiresAt<Date.now()} onClick={()=>void run(async()=>{if(!review)return;const n=await api.timesheetConfirm(connection.id,review.id,review.revision,review.token);if(alive.current){setReview(undefined);setMessage(n.message);setHistory(h=>h.map(x=>x.id===n.id?n:x));if(n.state!=='failed'){setDirty(false);setEditor(false);setEditing(undefined);setDetail(undefined)}}await refresh();if(n.state==='done'&&review.action.headerId&&['edit-line','add-line','delete-line'].includes(review.action.kind))await open(review.action.headerId)})}>{t('tsConfirm')}</Button></DialogActions></DialogBody></DialogSurface></Dialog>
  </section>
}
